---
services:
  frigate:
    container_name: frigate
    restart: unless-stopped
    stop_grace_period: 30s
    image: "{{ frigate_image }}"
    shm_size: "{{ frigate_shm_size }}"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - frigate_config:/config
      - frigate_media:/media/frigate
      - type: tmpfs # 1GB In-memory filesystem for recording segment storage
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    devices:
      - "{{ frigate_gpu_device }}:{{ frigate_gpu_device }}" # AMD / Intel GPU, needs to be updated for your hardware
    ports:
      - "127.0.0.1:5000:5000" # Frigate API, only accessible from localhost
      - "{{ frigate_port_gui }}:8971"
      - "{{ frigate_port_rtsp }}:8554"
      - "{{ frigate_port_webrtc_tcp }}:8555/tcp"
      - "{{ frigate_port_webrtc_udp }}:8555/udp"
    environment:
      FRIGATE_RTSP_PASSWORD: "{{ frigate_rtsp_pw }}"

volumes:
  frigate_config:
    name: frigate_config
  frigate_media:
    name: frigate_media
