---
# Tasks to deploy actual_budget service

- name: Deploy actual_budget
  block:
    - name: Ensure Compose project directory exists
      ansible.builtin.file:
        path: "{{ actual_budget_data_dir }}"
        state: directory
        mode: '0755'

    - name: Deploy docker-compose file
      ansible.builtin.template:
        src: docker-compose.yml
        dest: "{{ actual_budget_data_dir }}/docker-compose.yml"
        mode: '0600'
      register: actual_budget_compose_template

    - name: Start actual_budget service
      community.docker.docker_compose_v2:
        project_src: "{{ actual_budget_data_dir }}"
        state: present
        pull: always
      when: not ansible_check_mode

    - name: Append Actual to Tailscale services
      # noqa: var-naming[no-role-prefix]
      ansible.builtin.set_fact:
        tailscale_serve_services: "{{ tailscale_serve_services | combine({actual_budget_ts_service: actual_budget_port}) }}"
