---
# Common tasks applied to all homelabian-mini servers

- name: Common homelabian-mini setup
  block:
    - name: Update package cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Install common tools
      ansible.builtin.package:
        name:
          - git
          - curl
          - wget
          - jq
          - vim
          - less
          - btop
          - htop
          - tmux
          - screen
          - plocate             # locate tool to help find files
          - unzip
          - usbutils             # For lsusb and other USB tools
          - pciutils             # For lspci and other PCI tools
          - smartmontools        # For smartctl and other SMART tools
        state: present

    - name: Install common misc packages
      ansible.builtin.package:
        name:
          - locales             # For setting system locale
          - intel-microcode     # Microcode security updates for Intel CPUs
          - amd64-microcode     # Microcode security updates for AMD CPUs
          - etckeeper           # Tracks changes to `/etc` via git
        state: present

    - name: Enable en_US.UTF-8 in locale.gen
      ansible.builtin.lineinfile:
        path: /etc/locale.gen
        regexp: '^#?\s*en_US\.UTF-8\s+UTF-8'
        line: 'en_US.UTF-8 UTF-8'
      register: locale_configuration

    - name: Generate locale files
      ansible.builtin.command: locale-gen
      changed_when: true
      when: locale_configuration.changed

    - name: Set system-default locale
      ansible.builtin.lineinfile:
        path: /etc/default/locale
        regexp: '^LANG='
        line: 'LANG=en_US.UTF-8'
        mode: '0644'
        create: true
