# https://torsion.org/borgmatic/reference/configuration/

source_directories:
  - /home

repositories:
  - path: /mnt/usb_backup/borg_repo
    label: usb_backup
    storage_quota: 25G
    make_parent_directories: true
    encryption: none

keep_daily: 7
keep_weekly: 4
keep_monthly: 3

checks:
  - name: repository
  - name: archives

