---
# Set the default user's password on a newly flashed server

- name: Update default user password
  ansible.builtin.user:
    name: "{{ provision_user_new_user }}"
    password: "{{ provision_user_new_user_passwd_hash }}"
