---

- name: Reboot after dbus-broker installation
  ansible.builtin.reboot:
    msg: "Rebooting after dbus-broker installation"
    pre_reboot_delay: 5
    post_reboot_delay: 30
    reboot_timeout: 300

- name: Restart Mosquitto
  ansible.builtin.systemd:
    name: mosquitto
    state: restarted

- name: Restart Home Assistant
  community.docker.docker_container:
    name: home-assistant
    state: started
    restart: true
