---

# Main Ansible playbook to run configuration of servers in inventory

- name: Configure m710q server
  hosts: homelabian-m710q
  become: true

  # Setup various services via roles
  roles:
    # General setup
    - role: common-mini

    # Docker services
    - role: actual_budget
    - role: frigate
    - role: homarr
    - role: watchtower

    # Baremetal services
    # - role: borgmatic
