# Minimal borgmatic configuration template
# See https://torsion.org/borgmatic/docs/how-to/set-up-backups/

source_directories:
{% for directory in borgmatic_source_directories %}
  - {{ directory }}
{% endfor %}

repositories:
  - path: {{ borgmatic_repository_path }}
    label: local_backup
    encryption: {{ borgmatic_repository_encryption}}

encryption_passphrase: "{{ borgmatic_encryption_passphrase }}"

keep_daily: 5
keep_weekly: 3
keep_monthly: 5

checks:
  - name: repository
  - name: archives
